### ISSUE TITLE
Problem in Calling gen2vcf Function

### ISSUE THREAD

**Issue by sdmun20** [oncogenetics/oncofunco#6]
Recently, I am trying to convert IMPUTE2 gen file into VCF file using gen2vcf function in 
oncofunco package, but the following error message is displayed during the conversion process:

_Error in `[.data.frame`(x, i, j) : object 'V1' not found
Calls: gen2vcf -> gen2dose -> [ -> [.data.table -> [.data.frame
Execution halted_

I don't seem to have any problems with the gen file and source file. 
Could you please help me solve this problem?

[input.zip](https://github.com/oncogenetics/oncofunco/files/3032952/input.zip)
[gen2vcf.zip](https://github.com/oncogenetics/oncofunco/files/3032953/gen2vcf.zip)

**Comment by zx8754** [comment]
Thank you for reporting, @sdmun20 

This is now fixed, below command:

```R
library(oncofunco)

setwd("C:/Users/tdadaev/Desktop/oncofunco_issue_6")

GEN_FILE="example.gen"
SAMPLE_FILE="example.sample"
OUT_VCF_FILE="result.vcf"
OUT_VCF_HEADER="##fileformat=VCFv4.1"

gen2vcf(GEN_FILE, SAMPLE_FILE, "22", OUT_VCF_FILE, OUT_VCF_HEADER)
```

Will produce this file `result.vcf`:
```
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1A0	1A1	1A2	1A3	1A4
22	10000000	rs001	A	G	100	PASS	INFO	DS	2	2	2	1.5719	1.9791
22	10010000	rs002	A	G	100	PASS	INFO	DS	2	1	0	1	0
22	10020000	rs003	C	T	100	PASS	INFO	DS	0	1	2	0.9967	2
22	10030000	rs004	G	T	100	PASS	INFO	DS	0	1	2	1	2
22	10040000	rs005	C	G	100	PASS	INFO	DS	2	1	0	1	0
22	10050000	rs006	A	G	100	PASS	INFO	DS	1	1	0	1	0
22	10060000	rs007	G	T	100	PASS	INFO	DS	0	1	0	0	0
22	10070000	rs008	G	T	100	PASS	INFO	DS	0	1	2	1	2
22	10080000	rs009	G	T	100	PASS	INFO	DS	2	1	2	1	2
22	10090000	rs010	A	G	100	PASS	INFO	DS	2	1	0	1	0
22	10100000	rs011	C	T	100	PASS	INFO	DS	0	1	0	0	0
```

**Comment by sdmun20** [comment]
I changed the R version from 3.4.5 to 3.5.3 and created a successful vcf file using your command. However, i'm not completely sure if this is due to the version or not.
Anyway, thank you so much for your help.
I wish you good luck and success.
Thank you.

Windows 10용 메일에서 보냄

보낸 사람: Tokhir Dadaev
보낸 날짜: 2019년 4월 2일 화요일 오후 7:18
받는 사람: oncogenetics/oncofunco
참조: sdmun20; Mention
제목: Re: [oncogenetics/oncofunco] Problem in Calling gen2vcf Function (#6)

Thank you for reporting, @sdmun20
This is now fixed, below command:
library(oncofunco)

setwd("C:/Users/tdadaev/Desktop/oncofunco_issue_6")

GEN_FILE="example.gen"
SAMPLE_FILE="example.sample"
OUT_VCF_FILE="result.vcf"
OUT_VCF_HEADER="##fileformat=VCFv4.1"

gen2vcf(GEN_FILE, SAMPLE_FILE, "22", OUT_VCF_FILE, OUT_VCF_HEADER)
Will produce this file result.vcf:
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1A0	1A1	1A2	1A3	1A4
22	10000000	rs001	A	G	100	PASS	INFO	DS	2	2	2	1.5719	1.9791
22	10010000	rs002	A	G	100	PASS	INFO	DS	2	1	0	1	0
22	10020000	rs003	C	T	100	PASS	INFO	DS	0	1	2	0.9967	2
22	10030000	rs004	G	T	100	PASS	INFO	DS	0	1	2	1	2
22	10040000	rs005	C	G	100	PASS	INFO	DS	2	1	0	1	0
22	10050000	rs006	A	G	100	PASS	INFO	DS	1	1	0	1	0
22	10060000	rs007	G	T	100	PASS	INFO	DS	0	1	0	0	0
22	10070000	rs008	G	T	100	PASS	INFO	DS	0	1	2	1	2
22	10080000	rs009	G	T	100	PASS	INFO	DS	2	1	2	1	2
22	10090000	rs010	A	G	100	PASS	INFO	DS	2	1	0	1	0
22	10100000	rs011	C	T	100	PASS	INFO	DS	0	1	0	0	0
